map $host $app_root {
    default                     /usr/share/nginx/html/client;
    admin.marketplaceonline.site /usr/share/nginx/html/admin;
}

server {
    listen 8080;
    server_name _;

    root $app_root;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
